In [45]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np

In [8]:
data = pd.read_csv("F:\\coding\\Dataframe\\churn_large2.csv")
data

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,452,66,4,122388.10,1,1,1,46890.95,1
1,785,28,4,21186.14,1,1,0,100142.63,0
2,698,38,0,30313.87,4,1,0,11393.49,0
3,620,43,1,18751.38,1,0,1,14903.78,0
4,456,42,7,115434.56,4,1,1,115125.22,0
...,...,...,...,...,...,...,...,...,...
995,723,22,5,80188.35,4,0,0,55532.70,0
996,414,65,10,152621.67,4,1,0,16153.94,1
997,495,43,4,164632.17,3,1,1,73810.26,0
998,573,35,0,177777.48,3,1,1,107634.64,0
999,588,23,7,108901.15,2,0,0,161362.53,1

In [54]:
input_data = data.iloc[:, :- 1] 
output_data = data.iloc[:,-1]

In [56]:
input_data

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,452,66,4,122388.10,1,1,1,46890.95
1,785,28,4,21186.14,1,1,0,100142.63
2,698,38,0,30313.87,4,1,0,11393.49
3,620,43,1,18751.38,1,0,1,14903.78
4,456,42,7,115434.56,4,1,1,115125.22
...,...,...,...,...,...,...,...,...
995,723,22,5,80188.35,4,0,0,55532.70
996,414,65,10,152621.67,4,1,0,16153.94
997,495,43,4,164632.17,3,1,1,73810.26
998,573,35,0,177777.48,3,1,1,107634.64
999,588,23,7,108901.15,2,0,0,161362.53

In [57]:
ss = StandardScaler()
input_data = pd.DataFrame(ss.fit_transform(input_data), columns = input_data.columns)

In [58]:
ss.fit_transform(input_data)

array([[-1.04906523,  1.47971825, -0.26703291, ...,  0.98019606,
         0.98609664, -1.03280055],
       [ 1.30048867, -1.03962821, -0.26703291, ...,  0.98019606,
        -1.01409939, -0.05749819],
       [ 0.68664125, -0.3766423 , -1.5477663 , ...,  0.98019606,
        -1.01409939, -1.68293509],
       ...,
       [-0.74566938, -0.04514934, -0.26703291, ...,  0.98019606,
         0.98609664, -0.53977448],
       [-0.19532343, -0.57553807, -1.5477663 , ...,  0.98019606,
         0.98609664,  0.07971767],
       [-0.08948766, -1.37112116,  0.69351713, ..., -1.02020406,
        -1.01409939,  1.0637418 ]], shape=(1000, 8))

In [59]:
input_data

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-1.049065,1.479718,-0.267033,0.347746,-1.303044,0.980196,0.986097,-1.032801
1,1.300489,-1.039628,-0.267033,-1.385269,-1.303044,0.980196,-1.014099,-0.057498
2,0.686641,-0.376642,-1.547766,-1.228963,1.389195,0.980196,-1.014099,-1.682935
3,0.136295,-0.045149,-1.227583,-1.426963,-1.303044,-1.020204,0.986097,-1.618644
4,-1.020842,-0.111448,0.693517,0.228672,1.389195,0.980196,0.986097,0.216907
...,...,...,...,...,...,...,...,...
995,0.863034,-1.437420,0.053150,-0.374896,1.389195,-1.020204,-1.014099,-0.874527
996,-1.317182,1.413420,1.654067,0.865476,1.389195,0.980196,-1.014099,-1.595748
997,-0.745669,-0.045149,-0.267033,1.071148,0.491782,0.980196,0.986097,-0.539774
998,-0.195323,-0.575538,-1.547766,1.296252,0.491782,0.980196,0.986097,0.079718
999,-0.089488,-1.371121,0.693517,0.116791,-0.405631,-1.020204,-1.014099,1.063742

In [14]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size = 0.2, random_state =42)

In [15]:
import tensorflow

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
ann = Sequential()

In [20]:
ann.add(Dense(6,input_dim = 8,activation="relu")) 
ann.add(Dense(4,activation="relu"))
ann.add(Dense(2,activation="relu"))
ann.add(Dense(1,activation="sigmoid"))
ann.compile( optimizer='adam',loss="binary_crossentropy",metrics=['accuray'])

C:\Users\User\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [32]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

ann.fit(x_train, y_train, batch_size=100, epochs=50)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.5650 - loss: 0.6723
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5663 - loss: 0.6687
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5800 - loss: 0.6648
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5938 - loss: 0.6604
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6037 - loss: 0.6558
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6175 - loss: 0.6503
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6288 - loss: 0.6442
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6263 - loss: 0.6378
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6375 - loss: 0.6299
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6450 - loss: 0.6220
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6562 - loss: 0.6139
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6750 - loss: 0.6055
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6800 - loss: 0.5977
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6900 - loss: 0.5893
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7025 - loss: 0.5809
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7138 - loss: 0.5724
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7262 - loss: 0.5644
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7337 - loss: 0.5558
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7437 - loss: 0.5477
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7525 - loss: 0.5397
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7575 - loss: 0.5320
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7625 - loss: 0.5244
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7700 - loss: 0.5170
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7713 - loss: 0.5093
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7775 - loss: 0.5018
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7812 - loss: 0.4947
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7875 - loss: 0.4872
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7925 - loss: 0.4800
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7987 - loss: 0.4729
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7975 - loss: 0.4661
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.4593
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8125 - loss: 0.4527
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8175 - loss: 0.4464
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8263 - loss: 0.4404
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8313 - loss: 0.4344
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8350 - loss: 0.4285
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8475 - loss: 0.4226
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8500 - loss: 0.4168
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8537 - loss: 0.4113
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8587 - loss: 0.4057
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8600 - loss: 0.4004
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8662 - loss: 0.3951
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8737 - loss: 0.3900
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3851
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8788 - loss: 0.3801
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8825 - loss: 0.3751
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8838 - loss: 0.3706
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8900 - loss: 0.3660
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8913 - loss: 0.3613
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8925 - loss: 0.3572

In [49]:
x_test

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
521,1.102929,-0.177747,1.333884,-0.450351,-0.405631,0.980196,-1.014099,-0.902529
737,0.877146,0.551538,1.654067,1.440096,-0.405631,-1.020204,-1.014099,1.243081
740,0.178630,-0.177747,-1.227583,0.186928,-1.303044,-1.020204,0.986097,-1.007394
660,0.743087,-1.105927,1.333884,-1.728663,-0.405631,-1.020204,-1.014099,0.319199
411,0.178630,0.286344,0.373334,0.383979,-0.405631,-1.020204,-1.014099,0.857614
...,...,...,...,...,...,...,...,...
408,-1.296015,0.418941,0.053150,-0.139608,-1.303044,0.980196,-1.014099,-0.182033
332,-0.371716,0.551538,1.654067,1.081005,-1.303044,0.980196,-1.014099,0.635379
208,0.531415,-1.503718,0.693517,0.986154,1.389195,-1.020204,-1.014099,-0.565126
613,-0.886784,1.081927,0.693517,0.041233,1.389195,-1.020204,-1.014099,-0.252870
78,0.086905,-0.774434,-1.227583,-0.722514,-1.303044,0.980196,-1.014099,1.622438

In [33]:
prd = ann.predict(x_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

In [51]:
prd #34.92% is 1

array([[0.3492382]], dtype=float32)

In [52]:
type(prd)

numpy.ndarray

In [34]:
prd_data = []
for i in prd:
    if i[0] > 0.5:
        prd_data.append(1)
    else:
        prd_data.append(0)

In [35]:
prd1 = ann.predict(x_train)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [36]:
prd_data1 = []
for i in prd1:
    if i[0] > 0.5:
        prd_data1.append(1)
    else:
        prd_data1.append(0)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_test,prd_data)*100

89.5

In [47]:
prd = ann.predict(np.array([[1.102929, -0.177747, 1.333884, -0.450351,
               -0.405631, 0.980196, -1.014099, -0.902529]]))
prd_data = [] 
for i in prd :
    if i[0] > 0.5 :
        prd_data.append(1)
    else : 
        prd_data.append(0)

prd_data

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

[0]

In [60]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np
data = pd.read_csv("F:\\coding\\Dataframe\\churn_large2.csv")
input_data = data.iloc[:, :- 1] 
output_data = data.iloc[:,-1]
ss = StandardScaler()
input_data = pd.DataFrame(ss.fit_transform(input_data), columns = input_data.columns)
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size = 0.2, random_state =42)
import tensorflow
from keras.models import Sequential
from keras.layers import Dense
ann = Sequential()
ann.add(Dense(6,input_dim = 8,activation="relu")) 
ann.add(Dense(4,activation="relu"))
ann.add(Dense(2,activation="relu"))
ann.add(Dense(1,activation="sigmoid"))
ann.compile( optimizer='adam',loss="binary_crossentropy",metrics=['accuray'])
ann.fit(x_train, y_train, batch_size=100, epochs=50)
prd = ann.predict(x_test)
prd_data = []
for i in prd:
    if i[0] > 0.5:
        prd_data.append(1)
    else:
        prd_data.append(0)
prd1 = ann.predict(x_train)

C:\Users\User\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50

ValueError: Could not interpret metric identifier: accuray